export const ImportantCartsDetailsData = [
  {
    id: "1",
    mainHeader: "Gebührenfrei Mastercard Gold",

    firstHeader: "Allgemein",
    firstHeaderDetails: [
      {
        firstHeaderDetail: "Allgemeines",
        firstTitle1: "Kartenanbieter",
        firstDetail1: "gebührenfrei.de",
        firstTitle2: "Kartenname",
        firstDetail2: "Gebührenfrei Mastercard Gold",
        firstTitle3: "Kartengesellschaft",
        firstDetail3: "Mastercard",
        firstTitle4: "Karten-Art",
        firstDetail4: "Credit",
        firstTitle5: "Rechnungsausgleich",
        firstDetail5: "Überweisung, flexible Rückzahlung",

        secondHeaderDetail: "Grundgebühr & Zinsen",
        secondTitle1: "Kartengebühr pro Jahr",
        secondDetail1: "0 €",
        secondTitle2: "Eff. Jahreszins",
        secondDetail2: "24,69 %",

        thirdHeaderDetail: "Eigenschaften & Funktionen",
        thirdTitle1: "Girokonto bei Anbieter nötig",
        thirdDetail1: "Nein",
        thirdTitle2: "Partnerkarte",
        thirdDetail2: "Nein",
        thirdTitle3: "Kontaktlos bezahlen",
        thirdDetail3: "Ja",
        thirdTitle4: "Mobil bezahlen",
        // thirdDetail4: "Nein",

        fourthHeaderDetail: "Weitere Infos",
        fourthTitle1: "Haftung bei Kartenverlust",
        fourthDetail1: "50 €",
        fourthTitle2: "Ersatzkarte",
        fourthDetail2: "0 €",
      },
    ],

    secondHeader: "Bargeld / Bezahlung",
    secondHeaderDetails: [
      {
        firstHeaderDetail: "Gebühren bei Bezahlung",
        firstTitle1: "Karteneinsatz Inland",
        firstDetail1: "0,00 %",
        firstTitle2: "Karteneinsatz Euro-Zone",
        firstDetail2: "0,00 %",
        firstTitle3: "Karteneinsatz im Ausland",
        firstDetail3: "0,00 %",

        secondHeaderDetail: "Gebühren Bargeld abheben",
        secondTitle1: "Bargeld abheben Inland",
        secondDetail1: "0 %",
        secondTitle2: "Bargeld abheben Euro-Zone",
        secondDetail2: "0 %",
        secondTitle3: "Bargeld abheben Ausland",
        secondDetail3: "0 %",
      },
    ],

    thirdHeader: "Versicherung",
    thirdHeaderDetails: [
      {
        title1: "Auslandskrankenversicherung",
        detail1: "false",
        title2: "Reiseunfallversicherung",
        detail2: "true",
        title3: "Reiserücktrittsversicherung",
        detail3: "true",
        title4: "Reiserücktrittsversicherung",
        detail4: "true",
        title5: "Rechtsschutz für Mietwagen",
        detail5: "false",
        title6: "Haftpflicht für Mietwagen",
        detail6: "false",
        title7: "Vollkaskoversicherung für Mietwagen",
        detail7: "false",
      },
    ],

    fourthHeader: "Bonus",
    fourthHeaderDetails: [
      {
        title1: "Geld-Zurück-Bonus (Cashback)",
        detail1: "false",
        title2: "Bonus-Punktesystem",
        detail2: "false",
        title3: "Startguthaben",
        detail3: "false",
        title4: "Tankrabatt",
        detail4: "false",
        title5: "Rabatte auf Mietwagen",
        detail5: "true",
        title6: "Reiserabatte",
        detail6: "true",
        title7: "Hotelrabatte",
        detail7: "false",
      },
    ],

    fifthHeader: "Bewertung",
    fifthHeaderDetails: [
      {
        title1: "Gebühren",
        detail1: "8/11",
        title2: "Funktionen",
        detail2: "3/4",
        title3: "Zusatz-Leistungen",
        detail3: "5/10",
        title4: "Beantragung",
        detail4: "13/15",
        title5: "Gesamt:",
        detail5: "29/40",
      },
    ],
  },

  {
    id: "2",
    mainHeader: "Bank Norwegian Kreditkarte",

    firstHeader: "test",
    firstHeaderDetails: [
      {
        firstHeaderDetail: "Allgemeines",
        firstTitle1: "Kartenanbieter",
        firstDetail1: "gebührenfrei.de",
        firstTitle2: "Kartenname",
        firstDetail2: "Gebührenfrei Mastercard Gold",
        firstTitle3: "Kartengesellschaft",
        firstDetail3: "Mastercard",
        firstTitle4: "Karten-Art",
        firstDetail4: "Credit",
        firstTitle5: "Rechnungsausgleich",
        firstDetail5: "Überweisung, flexible Rückzahlung",

        secondHeaderDetail: "Grundgebühr & Zinsen",
        secondTitle1: "Kartengebühr pro Jahr",
        secondDetail1: "0 €",
        secondTitle2: "Eff. Jahreszins",
        secondDetail2: "24,69 %",

        thirdHeaderDetail: "Eigenschaften & Funktionen",
        thirdTitle1: "Girokonto bei Anbieter nötig",
        thirdDetail1: "Nein",
        thirdTitle2: "Partnerkarte",
        thirdDetail2: "Nein",
        thirdTitle3: "Kontaktlos bezahlen",
        thirdDetail3: "Ja",
        thirdTitle4: "Mobil bezahlen",
        // thirdDetail4: "Nein",

        fourthHeaderDetail: "Weitere Infos",
        fourthTitle1: "Haftung bei Kartenverlust",
        fourthDetail1: "50 €",
        fourthTitle2: "Ersatzkarte",
        fourthDetail2: "0 €",
      },
    ],

    secondHeader: "Bargeld / Bezahlung",
    secondHeaderDetails: [
      {
        firstHeaderDetail: "Gebühren bei Bezahlung",
        firstTitle1: "Karteneinsatz Inland",
        firstDetail1: "0,00 %",
        firstTitle2: "Karteneinsatz Euro-Zone",
        firstDetail2: "0,00 %",
        firstTitle3: "Karteneinsatz im Ausland",
        firstDetail3: "0,00 %",

        secondHeaderDetail: "Gebühren Bargeld abheben",
        secondTitle1: "Bargeld abheben Inland",
        secondDetail1: "0 %",
        secondTitle2: "Bargeld abheben Euro-Zone",
        secondDetail2: "0 %",
        secondTitle3: "Bargeld abheben Ausland",
        secondDetail3: "0 %",
      },
    ],
    
    thirdHeader: "Versicherung",
    thirdHeaderDetails: [
      {
        title1: "Auslandskrankenversicherung",
        detail1: "false",
        title2: "Reiseunfallversicherung",
        detail2: "true",
        title3: "Reiserücktrittsversicherung",
        detail3: "true",
        title4: "Reiserücktrittsversicherung",
        detail4: "true",
        title5: "Rechtsschutz für Mietwagen",
        detail5: "false",
        title6: "Haftpflicht für Mietwagen",
        detail6: "false",
        title7: "Vollkaskoversicherung für Mietwagen",
        detail7: "false",
      },
    ],

    fourthHeader: "Bonus",
    fourthHeaderDetails: [
      {
        title1: "Geld-Zurück-Bonus (Cashback)",
        detail1: "false",
        title2: "Bonus-Punktesystem",
        detail2: "false",
        title3: "Startguthaben",
        detail3: "false",
        title4: "Tankrabatt",
        detail4: "false",
        title5: "Rabatte auf Mietwagen",
        detail5: "true",
        title6: "Reiserabatte",
        detail6: "true",
        title7: "Hotelrabatte",
        detail7: "false",
      },
    ],

    fifthHeader: "Bewertung",
    fifthHeaderDetails: [
      {
        title1: "Gebühren",
        detail1: "8/11",
        title2: "Funktionen",
        detail2: "3/4",
        title3: "Zusatz-Leistungen",
        detail3: "5/10",
        title4: "Beantragung",
        detail4: "13/15",
        title5: "Gesamt:",
        detail5: "29/40",
      },
    ],
  },
];
